---
- block:
    - name: include preflight
      include_tasks: preflight.yml
      tags:
        - alertmanager_install
        - alertmanager_configure
        - alertmanager_run
    - name: include install
      include_tasks: install.yml
      tags:
        - alertmanager_install
    - name: selinux
      import_tasks: selinux.yml
      when: ansible_selinux.status == "enabled"
      tags:
        - alertmanager_configure
    - name: include configure
      include_tasks: configure.yml
      tags:
        - alertmanager_configure
  become: true
- name: ensure alertmanager service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: alertmanager
    state: started
    enabled: true
  tags:
    - alertmanager_run

- name: Flush alertmangaer handlers after run.
  meta: flush_handlers
